// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Load():Promise<main.LoadReturn>;

export function Open(arg1:string):Promise<string>;

export function Save(arg1:string):Promise<string>;
