// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Load() {
  return window['go']['main']['App']['Load']();
}

export function Open(arg1) {
  return window['go']['main']['App']['Open'](arg1);
}

export function Save(arg1) {
  return window['go']['main']['App']['Save'](arg1);
}
