// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Add(arg1:main.Item):Promise<string>;

export function Del(arg1:string):Promise<string>;

export function Edit(arg1:main.Item):Promise<string>;

export function GetList():Promise<Array<main.Item>>;

export function Greet(arg1:string):Promise<string>;

export function Open(arg1:string):Promise<string>;
