// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Add(arg1) {
  return window['go']['main']['App']['Add'](arg1);
}

export function Del(arg1) {
  return window['go']['main']['App']['Del'](arg1);
}

export function Edit(arg1) {
  return window['go']['main']['App']['Edit'](arg1);
}

export function GetList() {
  return window['go']['main']['App']['GetList']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function Open(arg1) {
  return window['go']['main']['App']['Open'](arg1);
}
